"""skill add success_count error_count last_called_at

Revision ID: 52436b9d5f47
Revises: dc2a5fe0e4f3
Create Date: 2026-08-02 17:31:21.995681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '52436b9d5f47'
down_revision: Union[str, None] = 'dc2a5fe0e4f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('success_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('skills', sa.Column('error_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('skills', sa.Column('last_called_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skills', 'last_called_at')
    op.drop_column('skills', 'error_count')
    op.drop_column('skills', 'success_count')
    # ### end Alembic commands ###
