"""persona_to_agent_角色升级为Agent完整配置

Revision ID: e4ea03bcb371
Revises: 6727223d45f9
Create Date: 2026-07-04 14:01:58.140487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e4ea03bcb371'
down_revision: Union[str, None] = '6727223d45f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_agent_configs_user_id', table_name='agent_configs')
    op.drop_table('agent_configs')
    # 为存量行提供默认值：先加列（server_default），再去掉 server_default 交还 ORM 控制
    op.add_column('agent_personas', sa.Column('memory_text', sa.Text(), nullable=False, server_default=sa.text("''")))
    op.add_column('agent_personas', sa.Column('tool_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('agent_personas', sa.Column('enable_knowledge', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('agent_personas', sa.Column('enable_memory', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('agent_personas', sa.Column('enable_web_search', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('agent_personas', sa.Column('enable_mcp', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('agent_personas', sa.Column('enable_active_recall', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('agent_personas', sa.Column('enable_cross_session', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('agent_personas', sa.Column('kb_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('agent_personas', sa.Column('skill_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('agent_personas', sa.Column('conversation_scope', sa.String(length=10), nullable=False, server_default=sa.text("'shared'")))
    op.add_column('agent_personas', sa.Column('context_window', sa.Integer(), nullable=False, server_default=sa.text('20')))
    op.add_column('agent_personas', sa.Column('human_mode', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('agent_personas', sa.Column('show_avatar', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # 去掉 server_default，后续由 ORM 控制默认值
    op.alter_column('agent_personas', 'memory_text', server_default=None)
    op.alter_column('agent_personas', 'tool_keys', server_default=None)
    op.alter_column('agent_personas', 'kb_ids', server_default=None)
    op.alter_column('agent_personas', 'skill_ids', server_default=None)
    op.add_column('conversations', sa.Column('persona_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_conversations_persona_id'), 'conversations', ['persona_id'], unique=False)
    op.create_foreign_key('fk_conversations_persona_id', 'conversations', 'agent_personas', ['persona_id'], ['id'], ondelete='SET NULL')
    # skills 从 user 级变为 persona 级，旧数据清空（不兼容）
    op.execute("DELETE FROM skills")
    op.add_column('skills', sa.Column('persona_id', sa.UUID(), nullable=False))
    op.add_column('skills', sa.Column('source', sa.String(length=10), nullable=False, server_default=sa.text("'custom'")))
    op.alter_column('skills', 'source', server_default=None)
    op.add_column('skills', sa.Column('import_hash', sa.String(length=64), nullable=True))
    op.drop_index('ix_skills_user_id', table_name='skills')
    op.create_index(op.f('ix_skills_persona_id'), 'skills', ['persona_id'], unique=False)
    op.drop_constraint('skills_user_id_fkey', 'skills', type_='foreignkey')
    op.create_foreign_key('fk_skills_persona_id', 'skills', 'agent_personas', ['persona_id'], ['id'], ondelete='CASCADE')
    op.drop_column('skills', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skills', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint('fk_skills_persona_id', 'skills', type_='foreignkey')
    op.create_foreign_key('skills_user_id_fkey', 'skills', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_skills_persona_id'), table_name='skills')
    op.create_index('ix_skills_user_id', 'skills', ['user_id'], unique=False)
    op.drop_column('skills', 'import_hash')
    op.drop_column('skills', 'source')
    op.drop_column('skills', 'persona_id')
    op.drop_constraint('fk_conversations_persona_id', 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_persona_id'), table_name='conversations')
    op.drop_column('conversations', 'persona_id')
    op.drop_column('agent_personas', 'show_avatar')
    op.drop_column('agent_personas', 'human_mode')
    op.drop_column('agent_personas', 'context_window')
    op.drop_column('agent_personas', 'conversation_scope')
    op.drop_column('agent_personas', 'skill_ids')
    op.drop_column('agent_personas', 'kb_ids')
    op.drop_column('agent_personas', 'enable_cross_session')
    op.drop_column('agent_personas', 'enable_active_recall')
    op.drop_column('agent_personas', 'enable_mcp')
    op.drop_column('agent_personas', 'enable_web_search')
    op.drop_column('agent_personas', 'enable_memory')
    op.drop_column('agent_personas', 'enable_knowledge')
    op.drop_column('agent_personas', 'tool_keys')
    op.drop_column('agent_personas', 'memory_text')
    op.create_table('agent_configs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('system_prompt', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('temperature', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('enable_knowledge', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_memory', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_web_search', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('show_avatar', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('enable_active_recall', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('enable_cross_session', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('human_mode', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='agent_configs_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='agent_configs_pkey')
    )
    op.create_index('ix_agent_configs_user_id', 'agent_configs', ['user_id'], unique=True)
    # ### end Alembic commands ###
