"""create_persona_ecosystem_tables

Revision ID: f260ac3868b8
Revises: 825f7138c68e
Create Date: 2026-07-18 15:52:24.031723

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f260ac3868b8'
down_revision: Union[str, None] = '825f7138c68e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('persona_diaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('diary_date', sa.Date(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=True),
    sa.Column('mood', sa.String(length=16), nullable=True),
    sa.Column('key_topics', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('key_insights', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['agent_personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'user_id', 'diary_date', name='uq_diary_date')
    )
    op.create_index(op.f('ix_persona_diaries_persona_id'), 'persona_diaries', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_diaries_user_id'), 'persona_diaries', ['user_id'], unique=False)
    op.create_table('persona_growth',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('xp', sa.Integer(), nullable=False),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('intimacy', sa.Float(), nullable=False),
    sa.Column('interaction_count', sa.Integer(), nullable=False),
    sa.Column('total_tokens_exchanged', sa.BigInteger(), nullable=False),
    sa.Column('total_tool_calls', sa.Integer(), nullable=False),
    sa.Column('consecutive_days', sa.Integer(), nullable=False),
    sa.Column('last_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('first_interaction_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('unlocked_traits', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['agent_personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'user_id', name='uq_persona_growth_pair')
    )
    op.create_index(op.f('ix_persona_growth_persona_id'), 'persona_growth', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_growth_user_id'), 'persona_growth', ['user_id'], unique=False)
    op.create_table('persona_market_listings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('seller_user_id', sa.UUID(), nullable=False),
    sa.Column('market_name', sa.String(length=64), nullable=False),
    sa.Column('market_description', sa.Text(), nullable=False),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('icon', sa.String(length=8), nullable=False),
    sa.Column('persona_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('downloads', sa.Integer(), nullable=False),
    sa.Column('rating_avg', sa.Float(), nullable=False),
    sa.Column('rating_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=16), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['agent_personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seller_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', name='uq_market_persona')
    )
    op.create_index(op.f('ix_persona_market_listings_is_active'), 'persona_market_listings', ['is_active'], unique=False)
    op.create_index(op.f('ix_persona_market_listings_persona_id'), 'persona_market_listings', ['persona_id'], unique=False)
    op.create_table('persona_milestones',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('persona_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('milestone_type', sa.String(length=32), nullable=False),
    sa.Column('level_at_trigger', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('triggered_by_message_id', sa.UUID(), nullable=True),
    sa.Column('memory_entities', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['persona_id'], ['agent_personas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('persona_id', 'user_id', 'milestone_type', 'occurred_at', name='uq_milestone_type_time')
    )
    op.create_index(op.f('ix_persona_milestones_persona_id'), 'persona_milestones', ['persona_id'], unique=False)
    op.create_index(op.f('ix_persona_milestones_user_id'), 'persona_milestones', ['user_id'], unique=False)
    op.create_table('persona_market_reviews',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('listing_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('rating BETWEEN 1 AND 5', name='ck_review_rating_range'),
    sa.ForeignKeyConstraint(['listing_id'], ['persona_market_listings.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('listing_id', 'user_id', name='uq_review_user')
    )
    op.create_index(op.f('ix_persona_market_reviews_listing_id'), 'persona_market_reviews', ['listing_id'], unique=False)
    op.add_column('agent_personas', sa.Column('cloned_from_id', sa.UUID(), nullable=True))
    op.add_column('agent_personas', sa.Column('clone_count', sa.Integer(), nullable=False, server_default=sa.text('0')))
    op.add_column('agent_personas', sa.Column('is_listed', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_personas', 'is_listed')
    op.drop_column('agent_personas', 'clone_count')
    op.drop_column('agent_personas', 'cloned_from_id')
    op.drop_index(op.f('ix_persona_market_reviews_listing_id'), table_name='persona_market_reviews')
    op.drop_table('persona_market_reviews')
    op.drop_index(op.f('ix_persona_milestones_user_id'), table_name='persona_milestones')
    op.drop_index(op.f('ix_persona_milestones_persona_id'), table_name='persona_milestones')
    op.drop_table('persona_milestones')
    op.drop_index(op.f('ix_persona_market_listings_persona_id'), table_name='persona_market_listings')
    op.drop_index(op.f('ix_persona_market_listings_is_active'), table_name='persona_market_listings')
    op.drop_table('persona_market_listings')
    op.drop_index(op.f('ix_persona_growth_user_id'), table_name='persona_growth')
    op.drop_index(op.f('ix_persona_growth_persona_id'), table_name='persona_growth')
    op.drop_table('persona_growth')
    op.drop_index(op.f('ix_persona_diaries_user_id'), table_name='persona_diaries')
    op.drop_index(op.f('ix_persona_diaries_persona_id'), table_name='persona_diaries')
    op.drop_table('persona_diaries')
    # ### end Alembic commands ###
