"""add_daily_xp_tracking

Revision ID: f735e480fec4
Revises: f260ac3868b8
Create Date: 2026-07-18 16:50:09.460739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f735e480fec4'
down_revision: Union[str, None] = 'f260ac3868b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('persona_growth', sa.Column('daily_xp', sa.Integer(), nullable=False))
    op.add_column('persona_growth', sa.Column('daily_xp_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('persona_growth', 'daily_xp_date')
    op.drop_column('persona_growth', 'daily_xp')
    # ### end Alembic commands ###
